title: EUNEH
description: 요즘 보고 듣는 것에 대하여 
url: "https://euneh.github.io"
baseurl: ""

remote_theme: jekyll/minima
minima:
  skin: auto
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme
